'use strict';
let restoreBundle=null;
$('#backup-export').addEventListener('click',()=>run(async()=>{const data=await api('backup/export');download('nelsonict-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data,null,2),'application/json');feedback('Backup downloaded. It contains voucher passwords; keep it private.');}));
$('#backup-file').addEventListener('change',e=>run(async()=>{restoreBundle=null;$('#backup-restore').hidden=true;$('#backup-preview').hidden=true;const file=e.target.files[0];if(!file)return;if(file.size>12*1024*1024)throw new Error('Backup limit is 12 MB.');const bundle=JSON.parse(await file.text());const result=await api('backup/preview',{backup:bundle});restoreBundle=bundle;$('#backup-preview').textContent=JSON.stringify(result,null,2);$('#backup-preview').hidden=false;$('#backup-restore').hidden=false;}));
$('#backup-restore').addEventListener('click',()=>run(async()=>{if(!restoreBundle)throw new Error('Select and preview a backup first.');if(!await confirmation('Restore local application data?','Disconnect the router first. Matching files will be replaced; a recovery copy is saved automatically.','RESTORE'))return;const result=await api('backup/restore',{backup:restoreBundle,confirmation:'RESTORE'});restoreBundle=null;$('#backup-restore').hidden=true;feedback(`Restored ${result.restored} files. Recovery copy: ${result.recovery}. Reload saved locations and templates before reconnecting.`);}));
function showOrders(result){$('#payment-orders').innerHTML=result.orders.length?result.orders.map(o=>`<tr><td>${escapeHTML(o.reference)}</td><td>${escapeHTML(o.provider||'paystack')}</td><td>${escapeHTML(o.price?.label||o.currency+' '+o.amount/100)}</td><td>${escapeHTML(o.domain)}</td><td>${escapeHTML(o.state)}</td><td>${escapeHTML(o.batch||'Not issued')}</td><td>${o.checkout_url?`<a href="${escapeHTML(o.checkout_url)}" target="_blank" rel="noopener noreferrer">Open checkout</a>`:'Unavailable'}</td></tr>`).join(''):'<tr><td colspan="7">No payment orders for this location.</td></tr>';}
$('#payment-create').addEventListener('click',()=>run(async()=>{const cfg=Object.fromEntries(new FormData($('#voucher-form')));cfg.email=$('#payment-email').value;cfg.provider=$('#payment-provider').value;cfg.customer_name=$('#payment-name').value;const result=await api('payments/create',cfg);showOrders(await api('payments/list'));feedback(`Checkout ${result.reference} created (${result.domain}). Share its link with the customer. Keep the backend connected to this location for automatic issuance.`);}));
$('#payment-refresh').addEventListener('click',()=>run(async()=>{showOrders(await api('payments/check'));feedback('Payments checked. Issued batches are available in Saved vouchers. Needs-review orders require checking the router and voucher archive before any manual replacement.');}));

