'use strict';
let diagnosticReview=null,diagnosticInput=null,diagnosticComments=false;
function showDiagnostic(review,comments=false){diagnosticReview=review;diagnosticComments=comments;$('#diag-share').checked=false;$('#diag-ai-result').textContent='Local review ready. AI analysis is optional.';$('#diag-evidence').textContent=JSON.stringify(review.ai_payload||review,null,2);$('#diag-fixes').replaceChildren(...(review.fixes||[]).map(f=>{const item=document.createElement('div');item.className='card';const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.dataset.fix=f.id;label.append(input,document.createTextNode(f.name+' · '+f.reason));const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='View exact changes';const pre=document.createElement('pre');pre.textContent=JSON.stringify({path:f.path,id:f.resource_id,before:f.before,after:f.after},null,2);details.append(summary,pre);item.append(label,details);return item;}));if(!(review.fixes||[]).length)$('#diag-fixes').textContent='No supported automatic fixes in this review. Inspect findings for manual steps.';}
$('#diag-collect').addEventListener('click',()=>run(async()=>{diagnosticInput=null;diagnosticReview=null;const r=await api('diagnostics/collect',{profile:$('#diag-profile').value.trim(),batch:$('#diag-batch').value.trim()});showDiagnostic(r);$('#diag-tickets').innerHTML=(r.tickets||[]).map(t=>`<tr><td>${t.protected?'Protected':`<input type="checkbox" data-legacy-id="${escapeHTML(t.id)}" aria-label="${escapeHTML('Select '+t.name)}">`}</td><td>${escapeHTML(t.name)}</td><td>${escapeHTML(t.profile)}</td><td>${escapeHTML(t.comment)}</td></tr>`).join('');feedback(`${r.fixes.length} supported repairs found. Review the evidence and changes.`);}));
$('#diag-file').addEventListener('change',e=>run(async()=>{diagnosticReview=null;diagnosticInput=null;$('#diag-tickets').replaceChildren();$('#diag-comment-ids').value='';const file=e.target.files[0];if(!file)return;if(file.size>262144)throw new Error('Export limit is 256 KB.');const input={kind:file.name.toLowerCase().endsWith('.rsc')?'rsc':'json',text:await file.text()};const review=await api('diagnostics/import',input);diagnosticInput=input;showDiagnostic(review);feedback('Read-only export projection loaded. Unsupported RSC lines are omitted.');}));
$('#diag-export').addEventListener('click',()=>{if(diagnosticReview)download('nelsonict-setup-review.json',JSON.stringify(diagnosticReview.ai_payload||diagnosticReview,null,2),'application/json');});
$('#diag-ai').addEventListener('click',()=>run(async()=>{if(!diagnosticReview||diagnosticComments)throw new Error('Collect or import setup evidence first.');if(!$('#diag-share').checked)throw new Error('Review the data and confirm sharing first.');const data=diagnosticInput?{...diagnosticInput,share:true}:{review_id:diagnosticReview.id,share:true};const result=await api('diagnostics/ai',data);$('#diag-ai-result').textContent=JSON.stringify(result,null,2);for(const input of document.querySelectorAll('[data-fix]'))input.checked=result.recommended_fix_ids.includes(input.dataset.fix);}));
$('#diag-select-all').addEventListener('click',()=>document.querySelectorAll('[data-fix]').forEach(x=>x.checked=true));
$('#diag-apply').addEventListener('click',()=>run(async()=>{if(!diagnosticReview?.id)throw new Error('Collect a live-router review or comment preview first.');if(!$('#diag-backup').checked)throw new Error('Confirm your router backup first.');const fixes=Array.from(document.querySelectorAll('[data-fix]:checked'),x=>x.dataset.fix);if(!fixes.length)throw new Error('Select a reviewed repair.');if(!await confirmation('Apply these router repairs?',`${fixes.length} reviewed changes. Ticket disabling disconnects affected sessions. Keep your backup available.`,'APPLY FIXES'))return;const id=diagnosticReview.id;diagnosticReview=null;const r=await api('diagnostics/apply',{review_id:id,fix_ids:fixes,comments:diagnosticComments,backup:true,confirmation:'APPLY FIXES'});$('#diag-fixes').textContent='Applied. Collect a fresh snapshot to verify.';feedback(`${r.count} repairs applied. ${r.notice}`);}));
$('#diag-comment-preview').addEventListener('click',()=>run(async()=>{diagnosticInput=null;showDiagnostic(await api('diagnostics/comments',{ids:$('#diag-comment-ids').value.split(',').map(x=>x.trim()).filter(Boolean),comment:$('#diag-comment').value}),true);}));

function legacySelection(){ $('#diag-comment-ids').value=Array.from(document.querySelectorAll('[data-legacy-id]:checked'),x=>x.dataset.legacyId).join(','); }
$('#diag-tickets').addEventListener('change',legacySelection);
$('#diag-all-legacy').addEventListener('click',()=>{document.querySelectorAll('[data-legacy-id]').forEach(x=>x.checked=true);legacySelection();});
