'use strict';
let salesResult=null,salesPage=0,cashVoucher=null;
const moneyText=(amount,code)=>amount===null||amount===undefined?'Unpriced':code+' '+(amount/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const localDay=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=new Date();$('#sales-from').value=localDay(new Date(today.getFullYear(),today.getMonth(),1));$('#sales-to').value=localDay(today);
function salesFilters(page){return {period:$('#sales-period').value,from:$('#sales-from').value,to:$('#sales-to').value,utc_offset:$('#sales-offset').value,profile:$('#sales-profile').value,status:$('#sales-status').value,batch:$('#sales-batch').value.trim(),query:$('#sales-query').value,page};}
async function loadSales(page=0){cashVoucher=null;$('#cash-sale-form').hidden=true;salesResult=await api('sales/report',salesFilters(page));salesPage=page;const old=$('#sales-profile').value;$('#sales-profile').replaceChildren(new Option('All profiles',''),...salesResult.profiles.map(p=>new Option(p,p)));if(salesResult.profiles.includes(old))$('#sales-profile').value=old;
 const c=salesResult.counts;$('#sales-count').textContent=`${salesResult.demo?'DEMO · ':''}Sold: ${c.sold||0} · Unsold: ${c.unsold||0} · Payment pending/review: ${c['payment-pending']||0} · Test: ${c.test||0} · Showing ${salesResult.vouchers.length} of ${salesResult.total} matching vouchers`;
 $('#sales-summary').innerHTML=salesResult.reports.length?salesResult.reports.map(r=>`<tr><td>${escapeHTML(r.period)}</td><td>${escapeHTML(r.profile)}</td><td>${r.sold}</td><td>${escapeHTML(r.currency)}</td><td>${escapeHTML(moneyText(r.amount_minor,r.currency))}</td></tr>`).join(''):'<tr><td colspan="5">No recorded sales in this date range.</td></tr>';
 $('#sales-inventory').innerHTML=salesResult.vouchers.length?salesResult.vouchers.map(v=>`<tr><td>${escapeHTML(v.username)}</td><td>${escapeHTML(v.batch)}</td><td>${escapeHTML(v.profile)}</td><td>${escapeHTML(v.status)}</td><td>${escapeHTML(moneyText(v.sale_amount??v.amount,v.sale_currency||v.currency))}</td><td>${escapeHTML(v.method||'—')}</td><td>${v.status==='unsold'?`<button class="secondary" data-cash="${v.id}">Record cash sale</button>`:v.method==='cash'?`<button class="secondary" data-unsell="${v.id}">Correct to unsold</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="7">No matching archived vouchers.</td></tr>';
}
for(const id of ['#sales-refresh','#sales-filter'])$(id).addEventListener('click',()=>run(()=>loadSales(0)));
$('#sales-prev').addEventListener('click',()=>run(()=>loadSales(Math.max(0,salesPage-1))));$('#sales-next').addEventListener('click',()=>run(()=>loadSales(salesResult&&(salesPage+1)*100<salesResult.total?salesPage+1:salesPage)));
$('#sales-inventory').addEventListener('click',e=>{const b=e.target.closest('[data-cash],[data-unsell]');if(!b)return;run(async()=>{if(b.dataset.unsell){if(!await confirmation('Correct this cash sale?','The sale is marked void in the ledger and excluded from totals. This is a recording correction, not a payment refund.','CORRECT'))return;await api('sales/unsell',{id:b.dataset.unsell,confirmation:'CORRECT'});await loadSales(salesPage);return;}cashVoucher=salesResult.vouchers.find(v=>v.id===b.dataset.cash);$('#cash-sale-title').textContent='Record cash sale · '+cashVoucher.username;$('#cash-amount').value=cashVoucher.amount===null?'':(cashVoucher.amount/100).toFixed(2);$('#cash-currency').value=cashVoucher.currency||'NGN';$('#cash-sale-form').hidden=false;$('#cash-sale-form').scrollIntoView({behavior:'smooth',block:'start'});});});
$('#cash-sale-form').addEventListener('submit',e=>{e.preventDefault();run(async()=>{if(!cashVoucher)throw new Error('Select a voucher first.');await api('sales/sell',{id:cashVoucher.id,amount:$('#cash-amount').value,currency:$('#cash-currency').value});await loadSales(salesPage);feedback('Cash sale recorded.');});});
$('#sales-csv').addEventListener('click',()=>{if(!salesResult)return;const cell=x=>{let v=String(x??'');if(/^[=+@\-\t\r]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"';};const rows=[['Period','Profile','Sold','Currency','Gross amount'],...salesResult.reports.map(r=>[r.period,r.profile,r.sold,r.currency,(r.amount_minor/100).toFixed(2)])];download('nelsonict-sales-'+(salesResult.demo?'demo-':'')+'report.csv',rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv');});
