'use strict';
let savedTemplates=[{id:'default',name:'Nelsonict classic',brand:'NELSONICT SERVICES LIMITED',heading:'Internet access',mode:'pin',accent:'#007f78',background:'#ffffff',layout:'a4',columns:3,contact:'Ask the hotspot attendant for assistance.',price:'',network:'Nelsonict Wi-Fi',footer:'Keep your ticket private.',show_policy:true,show_profile:false}];
let selectedTemplate='default',portalPlan=null,previewTimer=null;
function templateValue(){const form=$('#template-form');return {...Object.fromEntries(new FormData(form)),id:selectedTemplate,columns:Number(form.elements.columns.value),show_policy:form.elements.show_policy.checked,show_profile:form.elements.show_profile.checked};}
function fillTemplate(value){selectedTemplate=value.id||'default';const form=$('#template-form');for(const [key,v] of Object.entries(value)){if(!form.elements[key])continue;if(form.elements[key].type==='checkbox')form.elements[key].checked=v;else form.elements[key].value=v;}$('#portal-directory').value='nelsonict-'+form.elements.mode.value;portalPlan=null;$('#portal-plan-panel').hidden=true;}
function templateOptions(){for(const id of ['#template-select','#batch-template']){const old=$(id).value;$(id).replaceChildren(...savedTemplates.map(t=>{const option=document.createElement('option');option.value=t.id;option.textContent=t.name;return option;}));if(savedTemplates.some(x=>x.id===old))$(id).value=old;}if(savedTemplates.some(x=>x.id===selectedTemplate))$('#template-select').value=selectedTemplate;}
window.loadTemplates=async function(){const r=await api('templates/list');savedTemplates=r.templates;templateOptions();fillTemplate(savedTemplates.find(x=>x.id===selectedTemplate)||savedTemplates[0]);await previewTemplate();};
async function previewTemplate(){const r=await api('templates/render',{template:templateValue()});$('#template-preview').srcdoc=r.html;}
async function saveTemplate(asNew=false){const value=templateValue();if(asNew)value.id='default';const r=await api('templates/save',{template:value});selectedTemplate=r.template.id;const old=savedTemplates.findIndex(x=>x.id===selectedTemplate);if(old>=0)savedTemplates[old]=r.template;else savedTemplates.push(r.template);templateOptions();fillTemplate(r.template);feedback('Template saved. Select it when generating or printing vouchers.');await previewTemplate();}
$('#template-form').addEventListener('submit',e=>{e.preventDefault();run(()=>saveTemplate());});
$('#copy-template').addEventListener('click',()=>run(()=>saveTemplate(true)));
$('#template-select').addEventListener('change',()=>run(async()=>{fillTemplate(savedTemplates.find(x=>x.id===$('#template-select').value));await previewTemplate();}));
$('#load-template-list').addEventListener('click',()=>run(window.loadTemplates));
$('#preview-template').addEventListener('click',()=>run(previewTemplate));
$('#template-form').addEventListener('input',()=>{portalPlan=null;$('#portal-plan-panel').hidden=true;clearTimeout(previewTimer);previewTimer=setTimeout(()=>{if(!busy)run(previewTemplate);},500);});
$('#template-form [name=mode]').addEventListener('change',()=>{$('#portal-directory').value='nelsonict-'+$('#template-form').elements.mode.value;});
$('#export-template').addEventListener('click',()=>run(async()=>{await api('templates/render',{template:templateValue()});download('nelsonict-voucher-template.json',JSON.stringify(templateValue(),null,2),'application/json');}));
$('#import-template').addEventListener('change',e=>run(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>16000)throw new Error('Template JSON must be under 16 KB.');const t=JSON.parse(await file.text());t.id='default';await api('templates/render',{template:t});fillTemplate({...savedTemplates[0],...t});await previewTemplate();feedback('Template imported for preview. Save as new to keep it.');e.target.value='';}));
window.renderVoucherBatch=async function(){if(!batch.length)return;const t={...(savedTemplates.find(x=>x.id===$('#batch-template').value)||savedTemplates[0])};if(batch.some(v=>(v.username||v.pin)!==(v.password||v.pin)))t.mode='credentials';const r=await api('templates/render',{template:t,vouchers:batch,demo:!!router?.demo});$('#batch-preview').srcdoc=r.html;};
$('#batch-template').addEventListener('change',()=>{if(batch.length)run(window.renderVoucherBatch);});
$('#credential-mode').addEventListener('change',()=>{const pin=$('#credential-mode').value==='pin';$('#pin-length-field').hidden=!pin;$('#pair-format').hidden=pin;});
$('#download-portal').addEventListener('click',()=>run(async()=>{const result=await api('templates/export',{template:templateValue()});const bytes=Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0));download(result.filename,bytes,'application/zip');$('#portal-directory').value=result.directory;feedback('Optional portal overlay downloaded. Use Prepare direct installation to install from this app.');}));
for(const id of ['#portal-server','#portal-directory'])$(id).addEventListener('input',()=>{portalPlan=null;$('#portal-plan-panel').hidden=true;});
$('#check-portal').addEventListener('click',()=>run(async()=>{if(!router)throw new Error('Connect to a router before checking installation.');portalPlan=null;$('#portal-plan-panel').hidden=true;portalPlan=await api('portal/prepare',{server:$('#portal-server').value,template:templateValue()});$('#portal-plan-text').textContent=JSON.stringify({server:portalPlan.server,previous_folder:portalPlan.before,new_folder:portalPlan.directory,affected_servers:portalPlan.affected_servers,mode:portalPlan.mode,warnings:portalPlan.warnings},null,2);$('#portal-plan-panel').hidden=false;feedback('Installation prepared. Review the new folder, affected servers and warnings before uploading.');}));
$('#activate-portal').addEventListener('click',()=>run(async()=>{if(!portalPlan)throw new Error('Check the installation first.');if(!await confirmation('Upload and activate this customer login page?','Affected servers: '+portalPlan.affected_servers.join(', ')+'. Keep the old folder for recovery. PIN mode only works when username equals password.','INSTALL PORTAL'))return;const plan=portalPlan;portalPlan=null;$('#portal-plan-panel').hidden=true;await api('portal/deploy',{plan_id:plan.id,confirmation:'INSTALL PORTAL'});feedback('Portal uploaded, verified and activated. Test a customer login; restore the old folder from Change history if needed.');}));
if(token)run(async()=>{const r=await api('templates/list');savedTemplates=r.templates;templateOptions();});
