'use strict';
let umData=null,umPlan=null;
const umLabels={'user-manager':'Service settings','user-manager/router':'RADIUS router clients','user-manager/profile':'Profiles and prices','user-manager/limitation':'Speed, data and uptime limits','user-manager/profile-limitation':'Profile limit assignments','user-manager/user':'Users','user-manager/user/group':'Authentication groups','user-manager/user-profile':'User profile assignments','radius':'Router RADIUS client','radius/incoming':'Incoming disconnect requests','ip/hotspot/profile':'Hotspot RADIUS integration'};
const umDefaults={'user-manager':{enabled:'yes','use-profiles':'yes'},'user-manager/router':{name:'local-hotspot',address:'127.0.0.1','coa-port':'3799',protocol:'udp'},'radius':{address:'127.0.0.1',service:'hotspot','authentication-port':'1812','accounting-port':'1813',timeout:'1s'},'radius/incoming':{accept:'yes',port:'3799'},'ip/hotspot/profile':{'use-radius':'yes','radius-accounting':'yes','radius-interim-update':'1m'},'user-manager/profile':{'starts-when':'first-auth',validity:'1d',price:'500','override-shared-users':'1'},'user-manager/user':{group:'default','shared-users':'1',disabled:'no'}};
function umFields(values={}){const path=$('#um-menu').value;$('#um-fields').replaceChildren(...(umData?.fields[path]||[]).map(key=>{const label=document.createElement('label');label.textContent=key;const input=document.createElement('input');input.name=key;input.type=['password','secret','shared-secret'].includes(key)?'password':'text';input.autocomplete='off';input.value=values[key]==='[redacted]'?'':values[key]||'';input.placeholder='Omit to retain existing / use router default';label.append(input);return label;}));}
function umRender(){umPlan=null;$('#um-preview').textContent='Select a row to edit, or enter settings to create a record.';const path=$('#um-menu').value;const single=umData.singletons.includes(path);$('#um-action').value=single||path==='ip/hotspot/profile'?'update':'create';$('#um-id').value='';umFields(single?(umData.tables[path]||[])[0]:{});const query=$('#um-search').value.toLowerCase();const records=(umData.tables[path]||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(query)).sort((a,b)=>String(a.name||a.user||a['.id']||'').localeCompare(String(b.name||b.user||b['.id']||''),undefined,{numeric:true}));$('#um-rows').replaceChildren(...records.map(row=>{const card=document.createElement('div');card.className='card';const pre=document.createElement('pre');pre.textContent=JSON.stringify(row,null,2);card.append(pre);if(umData.fields[path]&&!single){const b=document.createElement('button');b.className='secondary';b.textContent='Edit this record';b.onclick=()=>{$('#um-id').value=row['.id'];$('#um-action').value='update';umFields(row);$('#um-fields').scrollIntoView({behavior:'smooth'});};card.append(b);}return card;}));$('#um-count').textContent=records.length+' records · '+(umData.unavailable.length?'Some operational menus unavailable':'Loaded');}
$('#um-refresh').onclick=()=>run(async()=>{umPlan=null;umData=await api('user-manager/list');const selected=$('#um-menu').value;$('#um-menu').replaceChildren(...Object.keys(umData.tables).map(p=>{const o=document.createElement('option');o.value=p;o.textContent=umLabels[p]||p;return o;}));if(selected&&umData.tables[selected])$('#um-menu').value=selected;umRender();});
$('#um-menu').onchange=()=>umRender();$('#um-search').oninput=()=>{if(umData)umRender();};
$('#um-defaults').onclick=()=>{if(!umData)return feedback('Load User Manager first.',true);umFields(umDefaults[$('#um-menu').value]||{});umPlan=null;};
$('#um-form').onsubmit=e=>{e.preventDefault();run(async()=>{if(!umData)throw Error('Load User Manager first.');const values={};for(const input of $('#um-fields').querySelectorAll('input'))if(input.value!=='')values[input.name]=input.value;umPlan=await api('user-manager/preview',{path:$('#um-menu').value,action:$('#um-action').value,id:$('#um-id').value,values});$('#um-preview').textContent=JSON.stringify(umPlan,null,2);for(const input of $('#um-fields').querySelectorAll('input[type=password]'))input.value='';});};
$('#um-apply').onclick=()=>run(async()=>{if(!umPlan)throw Error('Preview changes first.');if(!$('#um-backup').checked)throw Error('Confirm a router and User Manager database backup first.');if(!await confirmation('Apply User Manager changes?','Changes can affect authentication for every client using this profile. Review the exact operation.','APPLY USER MANAGER'))return;const id=umPlan.id;umPlan=null;const result=await api('user-manager/apply',{review_id:id,backup:true,confirmation:'APPLY USER MANAGER'});$('#um-preview').textContent=result.notice;feedback('Applied. Refresh User Manager before another change.');});
$('#remote-connect').onclick=()=>{$('#new-location').click();const form=$('#connection-form');form.elements.host.value=$('#remote-ip').value.trim();$('#router-transport').value=$('#remote-service').value;$('#router-transport').dispatchEvent(new Event('change'));view('connect');feedback('Enter credentials, verify the certificate and connect. You can save this remote location.');};
